ofxDepthStream: depth::Recorder Class Reference
depth::Recorder Class Reference
#include <Recorder.h>
Public Member Functions
~Recorder ()
void start (const std::string &name)
void start (std::ostream &ostream)
void stop ()
virtual void write (const void *data, size_t size) override
Updates the buffer with a new frame (triggers the output callback)
bool isRecording ()
Public Member Functions inherited from depth::Buffer
virtual FrameRef getRef ()
virtual void write (FrameRef f)
Updates the buffer with a new frame (triggers the output callback)
void clear ()
Clear the buffer (doesn't trigger the output callback)
void setOutputTo (Buffer *b)
Registers an output callback that updates the given buffer with this buffer's data whenever this buffer is updated.
Protected Member Functions
bool record (const void *data, uint32_t size)
Additional Inherited Members
Public Types inherited from depth::Buffer
typedef std::function< void(const void *, size_t)> NewDataCallback
A new data callback takes a void pointer to the memory block and a size_t with the number of bytes in the memory block.
Protected Attributes inherited from depth::Buffer
NewDataCallback newDataCallback =nullptr
FrameRef buffered =nullptr
Constructor & Destructor Documentation
~Recorder()
Recorder::~Recorder ()
Member Function Documentation
isRecording()
bool depth::Recorder::isRecording () inline
record()
bool Recorder::record (const void * data, uint32_t size) protected
Referenced by write().
start() [1/2]
void Recorder::start (const std::string & name)
start() [2/2]
void Recorder::start (std::ostream & ostream)
stop()
void Recorder::stop ()
Referenced by start(), and ~Recorder().
write()
virtual void depth::Recorder::write (const void * data, size_t size) inline override virtual
Updates the buffer with a new frame (triggers the output callback)
Reimplemented from depth::Buffer.
The documentation for this class was generated from the following files:
Recorder.h
Recorder.cpp