ofxDepthStream: depth::Transmitter Class Reference
depth::Transmitter Class Reference
Network stream transmitter class.
#include <Transmitter.h>
Public Member Functions
Transmitter (int port)
The constructor immediately starts the network server thread.
~Transmitter ()
The destructor stops the network-server if it's still running.
bool transmit (const void *data, size_t size)
Transmits a the given frame-data if the network-server has a connected client.
void stop (bool wait=true)
Stops the network server.
Protected Member Functions
void error (const char *msg)
void unbind ()
bool bind ()
void serverThread ()
bool transmitRaw (const void *data, size_t size)
Detailed Description
Network stream transmitter class.
The Transmitter class runs a network server on separate thread, which receives incoming connection requests over TCP and starts sending a (compressed) stream of Frames when a connection is established.
Constructor & Destructor Documentation
Transmitter()
Transmitter::Transmitter (int port)
The constructor immediately starts the network server thread.
~Transmitter()
Transmitter::~Transmitter ()
The destructor stops the network-server if it's still running.
Member Function Documentation
bind()
bool Transmitter::bind () protected
Referenced by serverThread().
error()
void depth::Transmitter::error (const char * msg) inline protected
Referenced by bind(), and serverThread().
serverThread()
void Transmitter::serverThread () protected
Referenced by Transmitter().
stop()
void Transmitter::stop (bool wait = true)
Stops the network server.
Referenced by ~Transmitter().
transmit()
bool Transmitter::transmit (const void * data, size_t size)
Transmits a the given frame-data if the network-server has a connected client.
transmitRaw()
bool Transmitter::transmitRaw (const void * data, size_t size) protected
Referenced by transmit().
unbind()
void Transmitter::unbind () protected
Referenced by stop().
The documentation for this class was generated from the following files:
Transmitter.h
Transmitter.cpp