ofxDepthStream: depth::Inflater Class Reference
depth::Inflater Class Reference
#include <Inflater.h>
Public Member Functions
~Inflater ()
void destroy ()
bool inflate (const void *data, size_t size)
size_t getSize () const
const void * getData () const
void * releaseData ()
size_t getFailCount () const
Protected Member Functions
void growTo (size_t to)
const void * decompress (const void *compressedBytes, unsigned int length)
std::ostream & cout ()
std::ostream & cerr ()
Constructor & Destructor Documentation
~Inflater()
depth::Inflater::~Inflater () inline
Member Function Documentation
cerr()
std::ostream& depth::Inflater::cerr () inline protected
cout()
std::ostream& depth::Inflater::cout () inline protected
decompress()
const void * Inflater::decompress (const void * compressedBytes, unsigned int length) protected
destroy()
void Inflater::destroy ()
Referenced by ~Inflater().
getData()
const void* depth::Inflater::getData () const inline
Referenced by depth::inflate().
getFailCount()
size_t depth::Inflater::getFailCount () const inline
getSize()
size_t depth::Inflater::getSize () const inline
Referenced by depth::inflate().
growTo()
void Inflater::growTo (size_t to) protected
inflate()
bool Inflater::inflate (const void * data, size_t size)
Referenced by depth::inflate().
releaseData()
void* depth::Inflater::releaseData () inline
The documentation for this class was generated from the following files:
Inflater.h
Inflater.cpp