ofxDepthStream: depth::Formatter Class Reference
depth::Formatter Class Reference
#include <CamInterface.h>
Public Member Functions
void process (openni::VideoStream &stream)
const unsigned char * getData () const
int getSize ()
Member Function Documentation
getData()
const unsigned char* depth::Formatter::getData () const inline
Referenced by depth::VideoStream::getData().
getSize()
int depth::Formatter::getSize () inline
Referenced by depth::VideoStream::getSize().
process()
void Formatter::process (openni::VideoStream & stream)
Referenced by depth::VideoStream::update().
The documentation for this class was generated from the following files:
CamInterface.h
CamInterface.cpp