ofxDepthStream: depth::Frame Class Reference
depth::Frame Class Reference
#include <Frame.h>
Public Types
typedef std::function< void(const void *, size_t)> InputFunc
Public Member Functions
Frame ()
Frame (size_t size)
Frame (const void *data, size_t size)
~Frame ()
const void * data ()
size_t size ()
template<typename ResultType >
ResultType convert (std::function< ResultType(const void *, size_t)> func)
The concert methods takes a function (ie.
Static Public Member Functions
static FrameRef ref (size_t size)
static FrameRef refToExternalData (const void *data, size_t size)
static FrameRef refWithData (void *data, size_t size)
Member Typedef Documentation
InputFunc
typedef std::function<void(const void*, size_t)> depth::Frame::InputFunc
Constructor & Destructor Documentation
Frame() [1/3]
depth::Frame::Frame () inline
Frame() [2/3]
depth::Frame::Frame (size_t size) inline
Frame() [3/3]
depth::Frame::Frame (const void * data, size_t size) inline
~Frame()
depth::Frame::~Frame () inline
Member Function Documentation
convert()
template<typename ResultType > ResultType depth::Frame::convert (std::function< ResultType(const void *, size_t)> func) inline
The concert methods takes a function (ie.
lambda) and, executes it and returns whatever type the lambda returns. This allows linking operations (frame->convert(...)->convert(...)-> etc.
data()
const void* depth::Frame::data () inline
Referenced by depth::compress(), convert(), depth::inflate(), refToExternalData(), and refWithData().
ref()
static FrameRef depth::Frame::ref (size_t size) inline static
Referenced by refWithData().
refToExternalData()
static FrameRef depth::Frame::refToExternalData (const void * data, size_t size) inline static
Referenced by depth::compress(), depth::inflate(), and depth::Buffer::write().
refWithData()
static FrameRef depth::Frame::refWithData (void * data, size_t size) inline static
Referenced by depth::convert_16bit_to_8bit(), depth::convert_32bit_to_8bit(), and depth::convertTo8bitGrayscaleData().
size()
size_t depth::Frame::size () inline
Referenced by depth::compress(), convert(), Frame(), depth::inflate(), ref(), refToExternalData(), and refWithData().
The documentation for this class was generated from the following file:
Frame.h