ofxDepthStream: ofxDepthStream Namespace Reference
ofxDepthStream Namespace Reference
Data Structures
struct DepthLoaderOpts
Options container for the loadDepth* methods.
struct MeshLoaderOpts
Functions
void loadDepthTexture16bit (ofTexture &tex, const void *data, size_t size, const DepthLoaderOpts &opts=DepthLoaderOpts())
populates the texture instance with 16-bit grayscale depth-image data from the given frame-data.
void loadDepthTexture32bit (ofTexture &tex, const void *data, size_t size, const DepthLoaderOpts &opts=DepthLoaderOpts())
populates the texture instance with 32-bit grayscale depth-image data from the given frame-data.
void loadDepthTexture (ofTexture &tex, const void *data, size_t size, const DepthLoaderOpts &opts=DepthLoaderOpts())
populates the texture instance with grayscale depth-image data from the given frame-data.
void loadDepthTexture (depth::Buffer &buffer, ofTexture &tex, const DepthLoaderOpts &opts=DepthLoaderOpts())
Populates texture with depth data from the buffer's current content and empties the buffer.
void loadMesh16bit (ofMesh &mesh, const void *data, size_t width, size_t height, const MeshLoaderOpts &opts=MeshLoaderOpts())
populates the mesh instance with 16-bit depth-image data.
void loadMesh32bit (ofMesh &mesh, const void *data, size_t width, size_t height, const MeshLoaderOpts &opts=MeshLoaderOpts())
UNTESTED populates the mesh instance with 32-bit depth-image data.
void loadMesh (ofMesh &mesh, const void *data, size_t size, const MeshLoaderOpts &opts=MeshLoaderOpts())
populates the mesh instance with depth-image data.
void loadMesh (depth::Buffer &buffer, ofMesh &mesh, const MeshLoaderOpts &opts=MeshLoaderOpts())
populates the mesh instance with depth-image data taken from the buffer's current content (if any).
void loadColorTexture (ofTexture &tex, const void *data, size_t size)
UNTESTED populates the texture with color-image data from the given frame-data.
void loadColorTexture (depth::Buffer &buffer, ofTexture &tex)
UNTESTED populates the texture with color-image data taken from the buffer's current content (if any).
Function Documentation
loadColorTexture() [1/2]
void ofxDepthStream::loadColorTexture (ofTexture & tex, const void * data, size_t size)
UNTESTED populates the texture with color-image data from the given frame-data.
It allocates the texture if necessary.
Referenced by loadColorTexture().
loadColorTexture() [2/2]
void ofxDepthStream::loadColorTexture (depth::Buffer & buffer, ofTexture & tex)
UNTESTED populates the texture with color-image data taken from the buffer's current content (if any).
It allocates the texture if necessary, and guesses the dimensions and bit-depth of the package size. It empties the buffer after using its content.
loadDepthTexture() [1/2]
void ofxDepthStream::loadDepthTexture (ofTexture & tex, const void * data, size_t size, const DepthLoaderOpts & opts = DepthLoaderOpts())
populates the texture instance with grayscale depth-image data from the given frame-data.
It allocates the texture if necessary and guesses the bit-depth of the data based on the size of the package.
Referenced by loadDepthTexture().
loadDepthTexture() [2/2]
void ofxDepthStream::loadDepthTexture (depth::Buffer & buffer, ofTexture & tex, const DepthLoaderOpts & opts = DepthLoaderOpts())
Populates texture with depth data from the buffer's current content and empties the buffer.
The texture is allocated if necessary, the resolution and bit-depth is guessed based on the size of the buffer's content.
loadDepthTexture16bit()
void ofxDepthStream::loadDepthTexture16bit (ofTexture & tex, const void * data, size_t size, const DepthLoaderOpts & opts = DepthLoaderOpts())
populates the texture instance with 16-bit grayscale depth-image data from the given frame-data.
It allocates the texture if necessary.
Referenced by loadDepthTexture().
loadDepthTexture32bit()
void ofxDepthStream::loadDepthTexture32bit (ofTexture & tex, const void * data, size_t size, const DepthLoaderOpts & opts = DepthLoaderOpts())
populates the texture instance with 32-bit grayscale depth-image data from the given frame-data.
It allocates the texture if necessary.
Referenced by loadDepthTexture().
loadMesh() [1/2]
void ofxDepthStream::loadMesh (ofMesh & mesh, const void * data, size_t size, const MeshLoaderOpts & opts = MeshLoaderOpts())
populates the mesh instance with depth-image data.
It allocates the texture if necessary, and guesses the dimensions and bit-depth of the package size
Referenced by loadMesh().
loadMesh() [2/2]
void ofxDepthStream::loadMesh (depth::Buffer & buffer, ofMesh & mesh, const MeshLoaderOpts & opts = MeshLoaderOpts())
populates the mesh instance with depth-image data taken from the buffer's current content (if any).
It allocates the texture if necessary, and guesses the dimensions and bit-depth of the package size. It empties the buffer after using its content.
loadMesh16bit()
void ofxDepthStream::loadMesh16bit (ofMesh & mesh, const void * data, size_t width, size_t height, const MeshLoaderOpts & opts = MeshLoaderOpts())
populates the mesh instance with 16-bit depth-image data.
It allocates the texture if necessary.
Referenced by loadMesh().
loadMesh32bit()
void ofxDepthStream::loadMesh32bit (ofMesh & mesh, const void * data, size_t width, size_t height, const MeshLoaderOpts & opts = MeshLoaderOpts())
UNTESTED populates the mesh instance with 32-bit depth-image data.
It allocates the texture if necessary.
Referenced by loadMesh().