ofxDepthStream: depth Namespace Reference
depth Namespace Reference
Data Structures
class Buffer
class CamInterface
The Whole purpose of this wrapper is to "hide" all OpenNI related stuff and replace it with placeholder code for the purpose of development.
class Compressor
class Formatter
class Frame
class Inflater
class Playback
class Receiver
class Recorder
class SimpleFrameListener
class Transmitter
class VideoStream
Typedefs
typedef std::shared_ptr< VideoStream > VideoStreamRef
typedef std::shared_ptr< Compressor > CompressorRef
typedef std::shared_ptr< Frame > FrameRef
typedef std::shared_ptr< Inflater > InflaterRef
typedef std::shared_ptr< Receiver > ReceiverRef
typedef std::shared_ptr< Transmitter > TransmitterRef
Functions
FrameRef compress (const void *data, size_t size)
FrameRef compress (Frame &instance)
FrameRef compress (FrameRef ref)
FrameRef inflate (const void *data, size_t size)
FrameRef inflate (Frame &instance)
FrameRef inflate (FrameRef ref)
FrameRef convert_32bit_to_8bit (size_t targetSize, const void *data)
FrameRef convert_16bit_to_8bit (size_t targetSize, const void *data)
FrameRef convertTo8bitGrayscaleData (size_t texSize, const void *data)
FrameRef convertTo8bitGrayscaleData (int texWidth, int texHeight, const void *data)
FrameRef convertTo8bitGrayscaleData (int texWidth, int texHeight, FrameRef ref)
std::function< FrameRef(const void *, size_t)> grayscale8bitConverter (int texWidth, int texHeight)
Generates converter lambda for specified width/height.
void emptyBuffer (Buffer &buf, Frame::InputFunc func)
void emptyAndInflateBuffer (Buffer &buf, Frame::InputFunc func)
int wasKeyboardHit ()
void Sleep (int millisecs)
Typedef Documentation
CompressorRef
typedef std::shared_ptr<Compressor> depth::CompressorRef
FrameRef
typedef std::shared_ptr<Frame> depth::FrameRef
InflaterRef
typedef std::shared_ptr<Inflater> depth::InflaterRef
ReceiverRef
typedef std::shared_ptr<Receiver> depth::ReceiverRef
TransmitterRef
typedef std::shared_ptr<Transmitter> depth::TransmitterRef
VideoStreamRef
typedef std::shared_ptr<VideoStream> depth::VideoStreamRef
Function Documentation
compress() [1/3]
FrameRef depth::compress (const void * data, size_t size)
Referenced by compress().
compress() [2/3]
FrameRef depth::compress (Frame & instance)
compress() [3/3]
FrameRef depth::compress (FrameRef ref)
convert_16bit_to_8bit()
FrameRef depth::convert_16bit_to_8bit (size_t targetSize, const void * data)
Referenced by ofxDepthStream::loadGrayscaleTexture().
convert_32bit_to_8bit()
FrameRef depth::convert_32bit_to_8bit (size_t targetSize, const void * data)
Referenced by ofxDepthStream::loadGrayscaleTexture().
convertTo8bitGrayscaleData() [1/3]
FrameRef depth::convertTo8bitGrayscaleData (size_t texSize, const void * data)
Referenced by convertTo8bitGrayscaleData(), and grayscale8bitConverter().
convertTo8bitGrayscaleData() [2/3]
FrameRef depth::convertTo8bitGrayscaleData (int texWidth, int texHeight, const void * data)
convertTo8bitGrayscaleData() [3/3]
FrameRef depth::convertTo8bitGrayscaleData (int texWidth, int texHeight, FrameRef ref)
emptyAndInflateBuffer()
void depth::emptyAndInflateBuffer (Buffer & buf, Frame::InputFunc func)
Referenced by ofxDepthStream::loadColorTexture(), ofxDepthStream::loadDepthTexture(), ofxDepthStream::loadGrayscaleTexture(), and ofxDepthStream::loadMesh().
emptyBuffer()
void depth::emptyBuffer (Buffer & buf, Frame::InputFunc func)
Referenced by emptyAndInflateBuffer().
grayscale8bitConverter()
std::function<FrameRef(const void*, size_t)> depth::grayscale8bitConverter (int texWidth, int texHeight)
Generates converter lambda for specified width/height.
inflate() [1/3]
FrameRef depth::inflate (const void * data, size_t size)
Referenced by depth::Inflater::decompress(), emptyAndInflateBuffer(), and inflate().
inflate() [2/3]
FrameRef depth::inflate (Frame & instance)
inflate() [3/3]
FrameRef depth::inflate (FrameRef ref)
Sleep()
void depth::Sleep (int millisecs)
Referenced by depth::Transmitter::serverThread(), and depth::Receiver::threadFunc().
wasKeyboardHit()
int depth::wasKeyboardHit ()